from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import requests
from bs4 import BeautifulSoup
import re
import html2text
from playwright.sync_api import sync_playwright

app = FastAPI(
    title="Job Announcement CV Processor API",
    description="A minimal FastAPI backend for processing job announcements and CVs",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:3001"],  # Frontend URLs
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class FetchJobRequest(BaseModel):
    url: str

@app.get("/")
def read_root():
    return {"message": "Welcome to the Job Announcement CV Processor API"}

@app.get("/health")
def health_check():
    return {"status": "healthy"}

@app.post("/fetch-job")
def fetch_job(request: FetchJobRequest):
    url = request.url
    if not url.startswith(('http://', 'https://')):
        raise HTTPException(status_code=400, detail="Invalid URL")
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            page.goto(url, timeout=30000)
            page.wait_for_load_state('networkidle', timeout=10000)
            
            # Scroll to bottom to load all lazy content
            page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            page.wait_for_timeout(2000)
            page.wait_for_load_state('networkidle', timeout=5000)
            
            # Get the full HTML content after all loading
            content = page.content()
            browser.close()
        
        return {"content": content}
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to fetch or process URL: {str(e)}")

@app.post("/analyze")
def analyze_cv(cv_file: UploadFile = File(...), job_content: str = Form(...)):
    if not cv_file:
        raise HTTPException(status_code=400, detail="CV file is required")
    if not job_content.strip():
        raise HTTPException(status_code=400, detail="Job content is required")
    
    # For now, just return OK
    return {"message": "OK"}

# Generated by Copilot