from fastapi import APIRouter, HTTPException, UploadFile, File, Form

router = APIRouter()

@router.post("/analyze")
def analyze_cv(cv_file: UploadFile = File(...), job_content: str = Form(...)):
    if not cv_file:
        raise HTTPException(status_code=400, detail="CV file is required")
    if not job_content.strip():
        raise HTTPException(status_code=400, detail="Job content is required")
    
    # For now, return mock analysis data
    mock_analysis = {
        "score": 78,
        "summary": "The candidate demonstrates strong technical skills and relevant experience that align well with the core requirements. There are some gaps in specific technologies mentioned in the job description, but the overall profile shows good potential for the role.",
        "strengths": [
            "Strong programming fundamentals with experience in multiple languages",
            "Demonstrated ability to work in agile environments",
            "Excellent communication skills evidenced by team collaboration experience",
            "Relevant industry experience that aligns with company focus",
        ],
        "gaps": [
            "Limited experience with specific cloud platforms mentioned (AWS/GCP)",
            "No direct experience with the required testing frameworks",
            "Could benefit from more leadership or mentoring experience",
        ],
        "skills": [
            {"name": "JavaScript", "status": "strong"},
            {"name": "React", "status": "strong"},
            {"name": "TypeScript", "status": "strong"},
            {"name": "Node.js", "status": "partial"},
            {"name": "Python", "status": "partial"},
            {"name": "AWS", "status": "missing"},
            {"name": "Docker", "status": "partial"},
            {"name": "GraphQL", "status": "missing"},
            {"name": "SQL", "status": "strong"},
            {"name": "Git", "status": "strong"},
        ],
        "experience": [
            {"category": "Technical Skills", "match": 82},
            {"category": "Industry Experience", "match": 75},
            {"category": "Education", "match": 90},
            {"category": "Soft Skills", "match": 85},
            {"category": "Leadership", "match": 60},
        ],
        "recommendations": [
            "Obtain AWS certification or complete relevant cloud projects to address the infrastructure gap",
            "Highlight any informal leadership or mentoring experiences in more detail",
            "Consider adding a projects section showcasing work with the missing technologies",
            "Tailor the professional summary to better reflect the specific role requirements",
        ],
    }
    return mock_analysis

# Generated by Copilot