from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from playwright.sync_api import sync_playwright
from llm.factory import get_llm_client

router = APIRouter()

class FetchJobRequest(BaseModel):
    url: str

@router.post("/fetch-job")
def fetch_job(request: FetchJobRequest):
    url = request.url
    if not url.startswith(('http://', 'https://')):
        raise HTTPException(status_code=400, detail="Invalid URL")
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            page.goto(url, timeout=30000)
            page.wait_for_load_state('networkidle', timeout=10000)
            
            # Scroll to bottom to load all lazy content
            page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            page.wait_for_timeout(2000)
            page.wait_for_load_state('networkidle', timeout=5000)
            
            # Get the full HTML content after all loading
            content = page.locator('body').inner_html()
            browser.close()
        
        # Truncate content if too long (approx 4000 tokens ~ 16k chars for grok-code-fast-1)
        if len(content) > 15000:
            content = content[:15000] + "... (content truncated for processing)"
        
        # Use LLM to extract job announcement as markdown
        client = get_llm_client()
        prompt = f"""
Extract the main job announcement content from the following HTML page. Focus on the job description, requirements, responsibilities, and company details. Remove headers, footers, navigation menus, ads, sidebars, and any unrelated content. Return the extracted content as clean, readable markdown. If the content is truncated, extract as much as possible from the provided portion. If no clear job announcement is found, return an empty string.

HTML:
{content}
"""
        extracted_content = client.generate_response(prompt)
        
        return {"content": extracted_content}
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to fetch or process URL: {str(e)}")

# Generated by Copilot