from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from playwright.sync_api import sync_playwright
from llm.factory import get_llm_client

router = APIRouter()

class FetchJobRequest(BaseModel):
    url: str

@router.post("/fetch-job")
def fetch_job(request: FetchJobRequest):
    url = request.url
    if not url.startswith(('http://', 'https://')):
        raise HTTPException(status_code=400, detail="Invalid URL")
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            page.goto(url, timeout=30000)
            page.wait_for_load_state('networkidle', timeout=10000)
            
            # Scroll to bottom to load all lazy content
            page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            page.wait_for_timeout(2000)
            page.wait_for_load_state('networkidle', timeout=5000)
            
            # Get the full HTML content after all loading
            content = page.locator('body').text_content()
            browser.close()
        
        # Use LLM to extract job announcement as markdown
        client = get_llm_client()
        prompt = f"""
Extract the main job announcement content from the webpage text provided below. Remove headers, footers, navigation, ads, and any unrelated content. Output the extracted content as clean Markdown, preserving the original structure, language, and formatting without reorganizing or adding sections. Do not summarize or shorten; provide the full extracted content.

CONTENT INPUT:
{content}
"""
        extracted_content = client.generate_response(prompt)
        
        return {"content": extracted_content}
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to fetch or process URL: {str(e)}")

# Generated by Copilot