from fastapi import APIRouter

router = APIRouter()

@router.get("/")
def read_root():
    return {"message": "Welcome to the Job Announcement CV Processor API"}

@router.get("/health")
def health_check():
    return {"status": "healthy"}

# Generated by Copilot