from fastapi import APIRouter
import logging

router = APIRouter()

logger = logging.getLogger(__name__)

@router.get("/")
def read_root():
    logger.info("Root endpoint accessed")
    return {"message": "Welcome to the Job Announcement CV Processor API"}

@router.get("/health")
def health_check():
    logger.info("Health check accessed")
    return {"status": "healthy"}

# Generated by Copilot