import os
from openai import OpenAI
from . import LLMClient

class AzureOpenAIClient(LLMClient):
    def __init__(self):
        self.client = OpenAI(
            api_key=os.getenv("AZURE_OPENAI_API_KEY"),
            base_url=os.getenv("AZURE_OPENAI_BASE_URL", "https://your-resource.openai.azure.com/openai/v1/")
        )

    def generate_response(self, prompt: str) -> str:
        response = self.client.chat.completions.create(
            model="gpt-4o",  # Deployment name
            messages=[{"role": "user", "content": prompt}],
            max_tokens=500
        )
        return response.choices[0].message.content

# Generated by Copilot